#@ load("common.lib.yml", "common")
#@ load("dev.lib.yml", "config")

server: #@ common.server()
management: #@ common.management()

spring:
  datasource: #@ config.datasource()
  jpa: #@ common.jpa()

logging: #@ common.logging()

custom:
  app:
    name: MySpringBootApp
    description: This is an example of a Spring Boot application with YAML configuration.
    version: 1.0.0
