#@ load("common.lib.yml", "common")
#@ load("sit.lib.yml", "config")

server: #@ common.server()
management: #@ common.management()

spring:
  datasource: #@ config.datasource()
  jpa: #@ common.jpa()

logging: #@ common.logging()